import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import type { Migration } from '@ailoud/core';
import { MIGRATIONS } from '@ailoud/core';

/**
 * Two guards against the same failure mode: a schema change that ships
 * without going through the migration list, or a migration edited after it
 * has already run on someone's machine.
 *
 * A database that already ran migration 4 will never run it again -- SQLite
 * only replays the migrations above its stored `user_version`. So an edited
 * migration 4 does not fail loudly; it means two machines sitting at the
 * same `user_version` with DIFFERENT schemas, which nothing here or in
 * SqliteStore would ever notice on its own. The lock file is the only thing
 * that would.
 *
 * schema.lock.json and schema.snapshot.sql are generated by
 * scripts/write-schema-snapshot.mjs (run it after adding a migration, never
 * to silence a failure here about an already-shipped one -- see
 * .agents/skills/check-migrations/SKILL.md).
 */

const here = dirname(fileURLToPath(import.meta.url));
const LOCK = join(here, 'schema.lock.json');
const SNAPSHOT = join(here, 'schema.snapshot.sql');

const lock = JSON.parse(readFileSync(LOCK, 'utf8')) as Record<string, string>;

/**
 * Hashes a migration's statements only, never the comments around them in
 * schema.ts. That is not a parsing choice -- the comments are TypeScript
 * comments outside the template-literal strings, so they were never part of
 * `migration.statements` at runtime, and editing one cannot change this
 * value. The comments explaining why a column or table exists are the house
 * style and must stay freely editable without touching the lock.
 *
 * A semicolon goes between statements, so that ["ab", "c"] and ["a", "bc"]
 * never collide -- no statement in schema.ts ends with one. Keep this in
 * exact step with the same-named function in
 * scripts/write-schema-snapshot.mjs -- both must compute the same thing
 * from the same MIGRATIONS, or a passing test here proves nothing.
 */
function fingerprint(migration: Migration): string {
  const hash = createHash('sha256');
  for (const statement of migration.statements) {
    hash.update(statement);
    hash.update(';');
  }
  return hash.digest('hex');
}

/** A fresh in-memory database with every migration applied, in order. */
function migratedDatabase(): DatabaseSync {
  const db = new DatabaseSync(':memory:');
  for (const migration of MIGRATIONS) {
    for (const statement of migration.statements) db.exec(statement);
  }
  return db;
}

/**
 * A deterministic text dump of the schema a database ends up with: every
 * table, index, and trigger that carries its own SQL, sorted by type then
 * name so the output does not depend on creation order. `sql IS NOT NULL`
 * excludes the automatic indexes SQLite creates for a composite PRIMARY KEY,
 * which store no SQL of their own and are implied by the table that owns
 * them.
 *
 * This is generated BY the migrations, never hand-edited, so it cannot drift
 * from them by construction -- only regeneration can change it, and
 * regeneration is scripts/write-schema-snapshot.mjs, which a reviewer sees
 * as a diff.
 */
function dumpSchema(db: DatabaseSync): string {
  const rows = db
    .prepare(`SELECT sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY type, name`)
    .all() as unknown as { sql: string }[];
  return rows.map((row) => `${row.sql};`).join('\n\n') + '\n';
}

describe('schema guard', () => {
  it('has a lock entry for every migration, and no extras', () => {
    expect(
      Object.keys(lock)
        .map(Number)
        .sort((a, b) => a - b),
    ).toEqual(MIGRATIONS.map((m) => m.version));
  });

  it('still matches the fingerprint of every shipped migration', () => {
    // A database that already ran version 4 will never run it again, so an
    // edited version 4 means two machines at the same user_version with
    // different schemas. Adding a migration means adding a lock line, which
    // is a visible diff in review.
    for (const migration of MIGRATIONS) {
      expect(fingerprint(migration)).toBe(lock[String(migration.version)]);
    }
  });

  it('produces exactly the snapshotted schema', () => {
    // Generated BY the migrations, so it cannot drift from them. Any
    // structural change fails here until the snapshot is regenerated, which
    // puts every schema change in front of a reviewer.
    const db = migratedDatabase();
    try {
      expect(dumpSchema(db)).toBe(readFileSync(SNAPSHOT, 'utf8'));
    } finally {
      db.close();
    }
  });
});
