import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import type { Migration } from '@ailoud/core';
import { MIGRATIONS } from '@ailoud/core';

/**
 * Two guards against the same failure mode: a schema change that ships
 * without going through the migration list, or a migration edited after it
 * has already run on someone's machine.
 *
 * A database that already ran migration 4 will never run it again -- SQLite
 * only replays the migrations above its stored `user_version`. So an edited
 * migration 4 does not fail loudly; it means two machines sitting at the
 * same `user_version` with DIFFERENT schemas, which nothing here or in
 * SqliteStore would ever notice on its own. The lock file is the only thing
 * that would.
 *
 * schema.lock.json and schema.snapshot.sql are generated by
 * scripts/write-schema-snapshot.mjs (run it after adding a migration, never
 * to silence a failure here about an already-shipped one -- see
 * .agents/skills/check-migrations/SKILL.md).
 */

const here = dirname(fileURLToPath(import.meta.url));
const LOCK = join(here, 'schema.lock.json');
const SNAPSHOT = join(here, 'schema.snapshot.sql');

const lock = JSON.parse(readFileSync(LOCK, 'utf8')) as Record<string, string>;

/**
 * Hashes a migration's statements only, never the comments around them in
 * schema.ts. That is not a parsing choice -- the comments are TypeScript
 * comments outside the template-literal strings, so they were never part of
 * `migration.statements` at runtime, and editing one cannot change this
 * value. The comments explaining why a column or table exists are the house
 * style and must stay freely editable without touching the lock.
 *
 * A record-separator character (0x1E), not ';', goes between statements.
 * A semicolon can appear INSIDE a statement -- every trigger body in
 * schema.ts (segment_ai, segment_ad, segment_fts_update) contains several,
 * between its BEGIN...END sub-statements -- so joining with ';' lets two
 * different splits of the same bytes collide on the same hash (e.g.
 * ["a;b", "c"] and ["a", "b;c"] both concatenate to "a;b;c;"). 0x1E cannot
 * appear in any SQL statement written in schema.ts, so this join has no such
 * collision. Keep this in exact step with the same-named function in
 * scripts/write-schema-snapshot.mjs -- both must compute the same thing
 * from the same MIGRATIONS, or a passing test here proves nothing.
 */
const FINGERPRINT_SEPARATOR = '\x1e';

function fingerprint(migration: Migration): string {
  const hash = createHash('sha256');
  for (const statement of migration.statements) {
    hash.update(statement);
    hash.update(FINGERPRINT_SEPARATOR);
  }
  return hash.digest('hex');
}

/**
 * True only if `versions` is exactly [1, 2, ..., versions.length], in that
 * order -- no gap, no duplicate, and no entry whose value disagrees with its
 * position. SCHEMA_VERSION (packages/core/src/db/schema.ts) is defined as
 * MIGRATIONS.length, which silently assumes exactly this. A gap -- say
 * versions [1, 2, 4], version 3 skipped by a typo when adding a new one --
 * lets SqliteStore.migrate write PRAGMA user_version = 4 while
 * SCHEMA_VERSION stays 3 (MIGRATIONS.length is still only 3 entries), so
 * pendingMigrations then refuses to reopen the very database that build just
 * created, as "newer than this build understands". This is asserted here,
 * as a loud development-time failure, rather than by redefining
 * SCHEMA_VERSION: that constant is what `user_version` MEANS in every
 * database that already exists, and changing its definition would be a
 * migration hazard of its own.
 */
function isContiguousFromOne(versions: readonly number[]): boolean {
  return versions.every((version, index) => version === index + 1);
}

/**
 * A fresh in-memory database with every migration applied, in order. Closes
 * `db` before rethrowing if any statement fails partway through: otherwise a
 * bad migration would leak the handle before it even reaches the caller's
 * own try/finally, since the caller never receives a reference to close.
 */
function migratedDatabase(): DatabaseSync {
  const db = new DatabaseSync(':memory:');
  try {
    for (const migration of MIGRATIONS) {
      for (const statement of migration.statements) db.exec(statement);
    }
  } catch (error) {
    db.close();
    throw error;
  }
  return db;
}

/**
 * A deterministic text dump of the schema a database ends up with: every
 * table, index, and trigger that carries its own SQL, sorted by type then
 * name so the output does not depend on creation order. `sql IS NOT NULL`
 * excludes the automatic indexes SQLite creates for a composite PRIMARY KEY,
 * which store no SQL of their own and are implied by the table that owns
 * them.
 *
 * Also excludes FTS5's shadow tables (segment_fts_config, _data, _docsize,
 * _idx: `type = 'table' AND name LIKE 'segment\_fts\_%'`). Those are not
 * written by any statement in schema.ts -- they are generated internally by
 * the FTS5 extension bundled with whichever SQLite build node:sqlite links,
 * which is still experimental in Node 24 with CI pinning only the major
 * version. Their exact DDL text (column names, WITHOUT ROWID, quoting
 * style) can change on a Node/SQLite upgrade with zero change to any
 * migration, which would fail this guard for a reason unrelated to its
 * subject -- and a guard that fails for reasons unrelated to its subject
 * teaches people to ignore it. `CREATE VIRTUAL TABLE segment_fts` itself is
 * NOT excluded (it doesn't match the shadow-table name pattern): the
 * declaration stays guarded, only its generated implementation detail does
 * not.
 *
 * This is generated BY the migrations, never hand-edited, so it cannot drift
 * from them by construction -- only regeneration can change it, and
 * regeneration is scripts/write-schema-snapshot.mjs, which a reviewer sees
 * as a diff.
 */
function dumpSchema(db: DatabaseSync): string {
  const rows = db
    .prepare(
      `SELECT sql FROM sqlite_master
       WHERE sql IS NOT NULL
         AND NOT (type = 'table' AND name LIKE 'segment\\_fts\\_%' ESCAPE '\\')
       ORDER BY type, name`,
    )
    .all() as unknown as { sql: string }[];
  return rows.map((row) => `${row.sql};`).join('\n\n') + '\n';
}

describe('schema guard', () => {
  it('has a lock entry for every migration, and no extras', () => {
    expect(
      Object.keys(lock)
        .map(Number)
        .sort((a, b) => a - b),
    ).toEqual(MIGRATIONS.map((m) => m.version));
  });

  it('still matches the fingerprint of every shipped migration', () => {
    // A database that already ran version 4 will never run it again, so an
    // edited version 4 means two machines at the same user_version with
    // different schemas. Adding a migration means adding a lock line, which
    // is a visible diff in review.
    for (const migration of MIGRATIONS) {
      expect(fingerprint(migration)).toBe(lock[String(migration.version)]);
    }
  });

  it('produces exactly the snapshotted schema', () => {
    // Generated BY the migrations, so it cannot drift from them. Any
    // structural change fails here until the snapshot is regenerated, which
    // puts every schema change in front of a reviewer.
    const db = migratedDatabase();
    try {
      expect(dumpSchema(db)).toBe(readFileSync(SNAPSHOT, 'utf8'));
    } finally {
      db.close();
    }
  });

  it('has version numbers contiguous from 1, with no gap and no duplicate', () => {
    expect(isContiguousFromOne(MIGRATIONS.map((m) => m.version))).toBe(true);
  });

  it('rejects a gap in version numbers', () => {
    expect(isContiguousFromOne([1, 2, 4])).toBe(false);
  });

  it('rejects a duplicate version number', () => {
    expect(isContiguousFromOne([1, 2, 2])).toBe(false);
  });

  it('rejects a version that disagrees with its position in the array', () => {
    expect(isContiguousFromOne([1, 3, 2])).toBe(false);
  });

  it('does not let statement content collide across the separator', () => {
    // Every trigger body in schema.ts contains internal semicolons, so if
    // the separator between statements were ';', two differently-split
    // statement lists could concatenate to the identical byte stream and
    // hash the same. This is not hypothetical: ['a;b', 'c'] and
    // ['a', 'b;c'] both produced 'a;b;c;' under the old ';' separator.
    const a: Migration = { version: 1, statements: ['a;b', 'c'] };
    const b: Migration = { version: 1, statements: ['a', 'b;c'] };
    expect(fingerprint(a)).not.toBe(fingerprint(b));
  });

  it('excludes FTS5 shadow tables from the snapshot but keeps segment_fts itself', () => {
    const snapshot = readFileSync(SNAPSHOT, 'utf8');
    expect(snapshot).toContain('CREATE VIRTUAL TABLE segment_fts');
    expect(snapshot).not.toMatch(/segment_fts_(config|data|docsize|idx)/);
  });
});
